import { Award, BookOpen, CheckCircle2, Clock, PlayCircle, Star, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useCourses } from "../context/CoursesContext";
import PageLayout from "../components/PageLayout";

export default function CourseDetails() {
  const courses = useCourses();
  const { id } = useParams();
  const course = courses.find((item) => String(item.id) === id);
  if (!course) return <PageLayout><div className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-3xl font-bold">Course not found</h1><Link to="/courses" className="mt-6 inline-block text-cyan-700">Browse all courses</Link></div></PageLayout>;
  const price = course.isFree || !course.price ? "Free" : `₹${course.price.sale}`;
  return <PageLayout>
    <section className="bg-slate-950 px-4 py-14 text-white"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.5fr_1fr] lg:items-center"><div><span className="text-sm font-semibold text-cyan-300">Development · All levels</span><h1 className="mt-3 text-3xl font-black sm:text-5xl">{course.name}</h1><p className="mt-5 max-w-3xl text-lg text-slate-300">Master in-demand skills through clear lessons, practical exercises, and a complete portfolio project.</p><div className="mt-6 flex flex-wrap gap-5 text-sm"><span className="flex gap-2"><Star className="text-amber-400" size={18} fill="currentColor"/>4.8 rating</span><span className="flex gap-2"><Users size={18}/>2,400 students</span><span className="flex gap-2"><Clock size={18}/>8 weeks</span></div><p className="mt-5 text-slate-300">Created by <strong className="text-white">{course.teacher}</strong></p></div><div className="overflow-hidden rounded-2xl bg-white p-3 text-slate-900"><img src={course.image} alt="" className="aspect-video w-full rounded-xl object-cover"/><div className="p-4"><div className="flex items-center justify-between"><strong className="text-3xl">{price}</strong><span className="text-sm text-slate-500">Lifetime access</span></div><Link to={`/checkout/${course.id}`} className="mt-5 block w-full rounded-xl bg-cyan-600 py-3 text-center font-bold text-white hover:bg-cyan-700">Enroll now</Link></div></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 py-14 lg:grid-cols-[1.5fr_1fr]"><div><h2 className="text-2xl font-bold">What you’ll learn</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{["Build real-world projects", "Understand core concepts", "Apply professional workflows", "Earn a completion certificate"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="shrink-0 text-emerald-500" size={20}/><span>{x}</span></div>)}</div><h2 className="mt-12 text-2xl font-bold">Course content</h2><div className="mt-5 space-y-3">{["Getting started", "Core foundations", "Building the project", "Testing and deployment"].map((x,i)=><div key={x} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4"><span className="flex items-center gap-3"><PlayCircle className="text-cyan-600"/>Module {i+1}: {x}</span><span className="text-sm text-slate-500">6 lessons</span></div>)}</div></div><aside className="h-fit rounded-2xl bg-cyan-50 p-6"><h2 className="text-xl font-bold">This course includes</h2><div className="mt-5 space-y-4 text-slate-700"><p className="flex gap-3"><BookOpen/>24 lessons</p><p className="flex gap-3"><Clock/>Lifetime access</p><p className="flex gap-3"><Award/>Certificate of completion</p></div></aside></section>
  </PageLayout>;
}
